CC = gcc
CFLAGS = -g -Wall -I./include
TESTS = $(patsubst test/%.c,bin/test_%,$(wildcard test/*.c))

vpath %.c src
vpath %.h include

all:	$(TESTS)

$(TESTS):	bin/test_%: test/%.c %.h test/test_lib.h
	$(CC) $(CFLAGS) -o $@ $< -lm

.PHONY:	clean
clean:
	-rm -f bin/main bin/test_* vgcore.*

.PHONY:	check
check:	$(TESTS)
	for TEST in $^; do\
		./$$TEST;\
	done

.PHONY:	leakcheck
leakcheck:	$(TESTS)
	@for TEST in $^; do\
		valgrind --leak-check=full --log-file="debug/$$TEST" $$TEST > /dev/null;\
		python3 tools/quiet.py "debug/$$TEST";\
	done
